# Generated by Django 3.1.4 on 2020-12-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201213_0306'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=200, verbose_name='Apellido')),
                ('document', models.CharField(max_length=11, verbose_name='Identificacion')),
                ('email', models.CharField(max_length=200, verbose_name='Correo electronico')),
                ('password', models.CharField(max_length=200, verbose_name='Contraseña')),
            ],
        ),
    ]
